### ISSUE TITLE
Is it possible to show only line values and skip column values ?

### ISSUE THREAD

**Issue by collegeimprovements** [ojroques/nvim-hardline#23]
Thanks a lot for hardline. It's the only lua statusline-plugin that worked for me out of the box 😅
Is it possible to only show line numbers and not row number ?
Is it possible to remove the dots as well ?
<img width="270" alt="Screenshot 2021-07-17 at 12 05 12 AM" src="https://user-images.githubusercontent.com/1519705/125993543-630e2afc-7599-4ef9-b9cf-e781f0672251.png">

**Comment by ojroques** [comment]
Hello!
I'm glad you like the plugin. If you want to change the part that display line and columns numbers, you need to either edit that file: [line.lua](https://github.com/ojroques/nvim-hardline/blob/main/lua/hardline/parts/line.lua) or create a new file in that directory and add it to the `sections` options of the [configuration table](https://github.com/ojroques/nvim-hardline#configuration).

If you choose the first option, in [line.lua](https://github.com/ojroques/nvim-hardline/blob/main/lua/hardline/parts/line.lua) you could just change that line:
https://github.com/ojroques/nvim-hardline/blob/17634e8250ee9b09aa7e023e6138052a10759146/lua/hardline/parts/line.lua#L29
to:
```lua
  return table.concat({get_line(), get_percent()}, ' ')
```
and to remove the dots, change this line:
https://github.com/ojroques/nvim-hardline/blob/17634e8250ee9b09aa7e023e6138052a10759146/lua/hardline/parts/line.lua#L5
to:
```lua
local padch = ''
```

I'm not willing to add these changes to the plugin since I prefer to have a part that display both lines/columns and because it would affect all users, so I encourage you to fork the plugin instead :)

**Comment by collegeimprovements** [comment]
Sure thing. If it's possible to get new config options, it would be great. 
But like you said and have mentioned in Readme file, I'll fork the plugin until there is a real demand for this config options from more users.

Thanks again for pointers.
