### ISSUE TITLE
`vim.lsp.diagnostic.get_count()` is deprecated in nvim v0.6.0+

### ISSUE THREAD

**Issue by yochem** [ojroques/nvim-hardline#29]
Starting from nvim version 0.6.0, `vim.lsp.diagnostic.get_count()` is deprecated. This can be fixed by the following changes to `./lua/hardline/parts/lsp.lua`:

```diff
diff --git a/lua/hardline/parts/lsp.lua b/lua/hardline/parts/lsp.lua
index 923f163..04d553b 100644
--- a/lua/hardline/parts/lsp.lua
+++ b/lua/hardline/parts/lsp.lua
@@ -2,7 +2,8 @@ local lsp = vim.lsp
 local fmt = string.format
 
 local function get_diagnostic(prefix, severity)
-  local count = lsp.diagnostic.get_count(0, severity)
+  local count = #vim.diagnostic.get(0, {severity=severity})
   if count < 1 then
     return ''
   end
@@ -10,11 +11,11 @@ local function get_diagnostic(prefix, severity)
 end
 
 local function get_error()
-  return get_diagnostic('E', 'Error')
+  return get_diagnostic('E', vim.diagnostic.severity.ERROR)
 end
 
 local function get_warning()
-  return get_diagnostic('W', 'Warning')
+  return get_diagnostic('W', vim.diagnostic.severity.WARN)
 end
 
 return {
```

I didn't  create a PR because I don't know if 1) you want to prepare it for v0.6.0 because you stated it's for you own use in the README, and 2) if the fix is welcome, how you want implement it to work on both v0.5 and v0.6.

Let me know if you want to create a PR for this!

**Comment by ojroques** [comment]
Yeah I saw that Neovim switched to a new API but I didn't want to bother with this since it didn't break the plugin. But you're totally right to raise this issue and I've updated the plugin, thanks!

I'm aware that the plugin is not for my own use anymore but it's only for new parts/themes that I prefer PRs. Otherwise I'm happy to fix bugs or deprecated code like this :)
